pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Github - Pull Request
    actions:
      merge:
        method: merge
  - name: automatic merge for Snyk pull requests
    conditions:
      - title~=^\[Snyk\]
      - head~=^snyk-fix
      - check-success~=^security/snyk
    actions:
      merge:
        method: merge
  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - check-success=Github - Pull Request
    actions:
      merge:
        method: merge
  - name: automatic merge for Requires.io pull requests
    conditions:
      - title~=^\[requires.io\]
      - head~=^requires-io
      - check-success=Github - Pull Request
    actions:
      merge:
        method: merge
  - name: automatic merge for Sonarcloud pull requests
    conditions:
      - author=sonarcloud-bot
      - check-success=Github - Pull Request
    actions:
      merge:
        method: merge
  - name: automatic merge for PyUp pull requests
    conditions:
      - author=pyup-bot
      - check-success=Github - Pull Request
    actions:
      merge:
        method: merge
  - name: automatic merge for Depfu pull requests
    conditions:
      - author=depfu[bot]
      - check-success=Github - Pull Request
    actions:
      merge:
        method: merge
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
      - check-success=Github - Pull Request
    actions:
      merge:
        method: merge